variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2 
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
services:
  - docker:dind

stages:
  - build
  # - test
  - package
  - deploy

gradle-build:
  image: gradle:alpine
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  artifacts:
    paths:
      - build/libs/*.jar


docker-build:
  image: docker:latest
  stage: package
  script:
  - docker build -t registry.gitlab.com/pavelgordon/hvv-client .
  - docker login -u pavelgordon -p $DOCKER_TOKEN registry.gitlab.com
  - docker push registry.gitlab.com/pavelgordon/hvv-client
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
  
deploy:
  image: node:latest
  stage: deploy
  script:
    # Setup SSH deploy keys
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh deploy@142.93.98.186 "$(< compose.sh)"
  only:
    - master


